//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDot.MsBuild.Tasks.MCorePackage
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeploymentPackageMetadata", Namespace="http://BlueDot.Mnow.Server.PackageDesign.DataContracts/2007/01")]
    [System.SerializableAttribute()]
    public partial class DeploymentPackageMetadata : BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageBase {
        
        private string DescriptionField;
        
        private int TypeIdField;
        
        private string TypeField;
        
        private System.DateTime CreatedWhenField;
        
        private string CreatedByField;
        
        private System.DateTime LastUpdatedWhenField;
        
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime CreatedWhen {
            get {
                return this.CreatedWhenField;
            }
            set {
                if ((this.CreatedWhenField.Equals(value) != true)) {
                    this.CreatedWhenField = value;
                    this.RaisePropertyChanged("CreatedWhen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime LastUpdatedWhen {
            get {
                return this.LastUpdatedWhenField;
            }
            set {
                if ((this.LastUpdatedWhenField.Equals(value) != true)) {
                    this.LastUpdatedWhenField = value;
                    this.RaisePropertyChanged("LastUpdatedWhen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeploymentPackageBase", Namespace="http://BlueDot.Mnow.Server.PackageDesign.DataContracts/2007/01")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageAddition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageMetadata))]
    public partial class DeploymentPackageBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeploymentPackageAddition", Namespace="http://BlueDot.Mnow.Server.PackageDesign.DataContracts/2007/01")]
    [System.SerializableAttribute()]
    public partial class DeploymentPackageAddition : BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageBase {
        
        private int HandlerIdField;
        
        private System.DateTime CreatedWhenField;
        
        private string CreatedByField;
        
        private byte[] ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HandlerId {
            get {
                return this.HandlerIdField;
            }
            set {
                if ((this.HandlerIdField.Equals(value) != true)) {
                    this.HandlerIdField = value;
                    this.RaisePropertyChanged("HandlerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime CreatedWhen {
            get {
                return this.CreatedWhenField;
            }
            set {
                if ((this.CreatedWhenField.Equals(value) != true)) {
                    this.CreatedWhenField = value;
                    this.RaisePropertyChanged("CreatedWhen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceHandlerModule", Namespace="http://BlueDotSolutions.MobileFramework.Server.PackageDesign.DataContracts/2007/0" +
        "1")]
    [System.SerializableAttribute()]
    public partial class DeviceHandlerModule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> ModuleDeploymentPackageIdField;
        
        private string HandlerNameField;
        
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ModuleDeploymentPackageId {
            get {
                return this.ModuleDeploymentPackageIdField;
            }
            set {
                if ((this.ModuleDeploymentPackageIdField.Equals(value) != true)) {
                    this.ModuleDeploymentPackageIdField = value;
                    this.RaisePropertyChanged("ModuleDeploymentPackageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string HandlerName {
            get {
                return this.HandlerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HandlerNameField, value) != true)) {
                    this.HandlerNameField = value;
                    this.RaisePropertyChanged("HandlerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceHandlerModuleAddition", Namespace="http://BlueDotSolutions.MobileFramework.Server.PackageDesign.DataContracts/2007/0" +
        "1")]
    [System.SerializableAttribute()]
    public partial class DeviceHandlerModuleAddition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string HandlerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int ModuleDeploymentPackageIdField;
        
        private string CreatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HandlerName {
            get {
                return this.HandlerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HandlerNameField, value) != true)) {
                    this.HandlerNameField = value;
                    this.RaisePropertyChanged("HandlerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ModuleDeploymentPackageId {
            get {
                return this.ModuleDeploymentPackageIdField;
            }
            set {
                if ((this.ModuleDeploymentPackageIdField.Equals(value) != true)) {
                    this.ModuleDeploymentPackageIdField = value;
                    this.RaisePropertyChanged("ModuleDeploymentPackageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
    [System.SerializableAttribute()]
    public partial class DefaultFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorIdField;
        
        private string ErrorMessageField;
        
        private System.Guid CorrelationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", ConfigurationName="MCorePackage.IPackageDesign")]
    public interface IPackageDesign {
        
        // CODEGEN: Generating message contract since the operation GetPackageList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPackageList", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetPackageListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetPackageListDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.GetPackageListResponse GetPackageList(BlueDot.MsBuild.Tasks.MCorePackage.GetPackageListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPackageContentRequest) of message GetPackageContentRequest does not match the default value (GetPackageContent)
        [System.ServiceModel.OperationContractAttribute(Action="GetPackageContent", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetPackageContentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetPackageContentDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.GetPackageContentResponse GetPackageContent(BlueDot.MsBuild.Tasks.MCorePackage.GetPackageContentRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AddPackageRequest) of message AddPackageRequest does not match the default value (AddPackage)
        [System.ServiceModel.OperationContractAttribute(Action="AddPackage", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "AddPackageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "AddPackageDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.AddPackageResponse AddPackage(BlueDot.MsBuild.Tasks.MCorePackage.AddPackageRequest request);
        
        // CODEGEN: Generating message contract since the operation GetDeviceHandlers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetDeviceHandlers", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetDeviceHandlersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetDeviceHandlersDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.GetDeviceHandlerModulesResponse GetDeviceHandlers(BlueDot.MsBuild.Tasks.MCorePackage.GetDeviceHandlersRequest request);
        
        // CODEGEN: Generating message contract since the operation RemovePackage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RemovePackage", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "RemovePackageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "RemovePackageDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.RemovePackageResponse RemovePackage(BlueDot.MsBuild.Tasks.MCorePackage.RemovePackageRequest request);
        
        // CODEGEN: Generating message contract since the operation AddDependencies is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AddDependencies", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "AddDependenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "AddDependenciesDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.AddDependenciesResponse AddDependencies(BlueDot.MsBuild.Tasks.MCorePackage.AddDependenciesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetDependenciesRequest) of message GetDependenciesRequest does not match the default value (GetDependencies)
        [System.ServiceModel.OperationContractAttribute(Action="GetDependencies", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetDependenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "GetDependenciesDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.GetDependenciesResponse GetDependencies(BlueDot.MsBuild.Tasks.MCorePackage.GetDependenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation RemoveDependency is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RemoveDependency", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "RemoveDependencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "RemoveDependencyDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.RemoveDependencyResponse RemoveDependency(BlueDot.MsBuild.Tasks.MCorePackage.RemoveDependencyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RegisterDeviceHandlerRequest) of message RegisterDeviceHandlerRequest does not match the default value (RegisterDeviceHandler)
        [System.ServiceModel.OperationContractAttribute(Action="RegisterDeviceHandler", ReplyAction="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "RegisterDeviceHandlerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlueDot.MsBuild.Tasks.MCorePackage.DefaultFaultContract), Action="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01/IPackageDesign/" +
            "RegisterDeviceHandlerDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://FaultContracts/Default/DefaultFaultContract")]
        BlueDot.MsBuild.Tasks.MCorePackage.RegisterDeviceHandlerResponse RegisterDeviceHandler(BlueDot.MsBuild.Tasks.MCorePackage.RegisterDeviceHandlerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackageListRequest {
        
        public GetPackageListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPackageListResponse", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class GetPackageListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageMetadata[] PackageList;
        
        public GetPackageListResponse() {
        }
        
        public GetPackageListResponse(BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageMetadata[] PackageList) {
            this.PackageList = PackageList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPackageContentRequest", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class GetPackageContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public int PackageId;
        
        public GetPackageContentRequest() {
        }
        
        public GetPackageContentRequest(int PackageId) {
            this.PackageId = PackageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPackageContentResponse", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class GetPackageContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public byte[] Content;
        
        public GetPackageContentResponse() {
        }
        
        public GetPackageContentResponse(byte[] Content) {
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPackageRequest", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class AddPackageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageAddition PackageToAdd;
        
        public AddPackageRequest() {
        }
        
        public AddPackageRequest(BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageAddition PackageToAdd) {
            this.PackageToAdd = PackageToAdd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPackageResponse", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class AddPackageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public int PackageId;
        
        public AddPackageResponse() {
        }
        
        public AddPackageResponse(int PackageId) {
            this.PackageId = PackageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceHandlersRequest {
        
        public GetDeviceHandlersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeviceHandlerModulesResponse", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class GetDeviceHandlerModulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public BlueDot.MsBuild.Tasks.MCorePackage.DeviceHandlerModule[] DeviceHandlerList;
        
        public GetDeviceHandlerModulesResponse() {
        }
        
        public GetDeviceHandlerModulesResponse(BlueDot.MsBuild.Tasks.MCorePackage.DeviceHandlerModule[] DeviceHandlerList) {
            this.DeviceHandlerList = DeviceHandlerList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemovePackageRequest", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class RemovePackageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public int PackageId;
        
        public RemovePackageRequest() {
        }
        
        public RemovePackageRequest(int PackageId) {
            this.PackageId = PackageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePackageResponse {
        
        public RemovePackageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDependenciesRequest", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class AddDependenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public int DeploymentPackageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=1)]
        public int[] DependencyList;
        
        public AddDependenciesRequest() {
        }
        
        public AddDependenciesRequest(int DeploymentPackageId, int[] DependencyList) {
            this.DeploymentPackageId = DeploymentPackageId;
            this.DependencyList = DependencyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDependenciesResponse {
        
        public AddDependenciesResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDependenciesRequest", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class GetDependenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public int DeploymentPackageId;
        
        public GetDependenciesRequest() {
        }
        
        public GetDependenciesRequest(int DeploymentPackageId) {
            this.DeploymentPackageId = DeploymentPackageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDependenciesResponse", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class GetDependenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageMetadata[] DependencyList;
        
        public GetDependenciesResponse() {
        }
        
        public GetDependenciesResponse(BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageMetadata[] DependencyList) {
            this.DependencyList = DependencyList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveDependencyRequest", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class RemoveDependencyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public int PackageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=1)]
        public int DependentPackageId;
        
        public RemoveDependencyRequest() {
        }
        
        public RemoveDependencyRequest(int PackageId, int DependentPackageId) {
            this.PackageId = PackageId;
            this.DependentPackageId = DependentPackageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDependencyResponse {
        
        public RemoveDependencyResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterDeviceHandlerRequest", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class RegisterDeviceHandlerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public BlueDot.MsBuild.Tasks.MCorePackage.DeviceHandlerModuleAddition NewHandlerModule;
        
        public RegisterDeviceHandlerRequest() {
        }
        
        public RegisterDeviceHandlerRequest(BlueDot.MsBuild.Tasks.MCorePackage.DeviceHandlerModuleAddition NewHandlerModule) {
            this.NewHandlerModule = NewHandlerModule;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterDeviceHandlerResponse", WrapperNamespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", IsWrapped=true)]
    public partial class RegisterDeviceHandlerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BlueDot.Mnow.Server.PackageDesign.ServiceContracts/2007/01", Order=0)]
        public int DeviceHandlerId;
        
        public RegisterDeviceHandlerResponse() {
        }
        
        public RegisterDeviceHandlerResponse(int DeviceHandlerId) {
            this.DeviceHandlerId = DeviceHandlerId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPackageDesignChannel : BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PackageDesignClient : System.ServiceModel.ClientBase<BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign>, BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign {
        
        public PackageDesignClient() {
        }
        
        public PackageDesignClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PackageDesignClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageDesignClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackageDesignClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.GetPackageListResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.GetPackageList(BlueDot.MsBuild.Tasks.MCorePackage.GetPackageListRequest request) {
            return base.Channel.GetPackageList(request);
        }
        
        public BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageMetadata[] GetPackageList() {
            BlueDot.MsBuild.Tasks.MCorePackage.GetPackageListRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.GetPackageListRequest();
            BlueDot.MsBuild.Tasks.MCorePackage.GetPackageListResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).GetPackageList(inValue);
            return retVal.PackageList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.GetPackageContentResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.GetPackageContent(BlueDot.MsBuild.Tasks.MCorePackage.GetPackageContentRequest request) {
            return base.Channel.GetPackageContent(request);
        }
        
        public byte[] GetPackageContent(int PackageId) {
            BlueDot.MsBuild.Tasks.MCorePackage.GetPackageContentRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.GetPackageContentRequest();
            inValue.PackageId = PackageId;
            BlueDot.MsBuild.Tasks.MCorePackage.GetPackageContentResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).GetPackageContent(inValue);
            return retVal.Content;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.AddPackageResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.AddPackage(BlueDot.MsBuild.Tasks.MCorePackage.AddPackageRequest request) {
            return base.Channel.AddPackage(request);
        }
        
        public int AddPackage(BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageAddition PackageToAdd) {
            BlueDot.MsBuild.Tasks.MCorePackage.AddPackageRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.AddPackageRequest();
            inValue.PackageToAdd = PackageToAdd;
            BlueDot.MsBuild.Tasks.MCorePackage.AddPackageResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).AddPackage(inValue);
            return retVal.PackageId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.GetDeviceHandlerModulesResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.GetDeviceHandlers(BlueDot.MsBuild.Tasks.MCorePackage.GetDeviceHandlersRequest request) {
            return base.Channel.GetDeviceHandlers(request);
        }
        
        public BlueDot.MsBuild.Tasks.MCorePackage.DeviceHandlerModule[] GetDeviceHandlers() {
            BlueDot.MsBuild.Tasks.MCorePackage.GetDeviceHandlersRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.GetDeviceHandlersRequest();
            BlueDot.MsBuild.Tasks.MCorePackage.GetDeviceHandlerModulesResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).GetDeviceHandlers(inValue);
            return retVal.DeviceHandlerList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.RemovePackageResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.RemovePackage(BlueDot.MsBuild.Tasks.MCorePackage.RemovePackageRequest request) {
            return base.Channel.RemovePackage(request);
        }
        
        public void RemovePackage(int PackageId) {
            BlueDot.MsBuild.Tasks.MCorePackage.RemovePackageRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.RemovePackageRequest();
            inValue.PackageId = PackageId;
            BlueDot.MsBuild.Tasks.MCorePackage.RemovePackageResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).RemovePackage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.AddDependenciesResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.AddDependencies(BlueDot.MsBuild.Tasks.MCorePackage.AddDependenciesRequest request) {
            return base.Channel.AddDependencies(request);
        }
        
        public void AddDependencies(int DeploymentPackageId, int[] DependencyList) {
            BlueDot.MsBuild.Tasks.MCorePackage.AddDependenciesRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.AddDependenciesRequest();
            inValue.DeploymentPackageId = DeploymentPackageId;
            inValue.DependencyList = DependencyList;
            BlueDot.MsBuild.Tasks.MCorePackage.AddDependenciesResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).AddDependencies(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.GetDependenciesResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.GetDependencies(BlueDot.MsBuild.Tasks.MCorePackage.GetDependenciesRequest request) {
            return base.Channel.GetDependencies(request);
        }
        
        public BlueDot.MsBuild.Tasks.MCorePackage.DeploymentPackageMetadata[] GetDependencies(int DeploymentPackageId) {
            BlueDot.MsBuild.Tasks.MCorePackage.GetDependenciesRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.GetDependenciesRequest();
            inValue.DeploymentPackageId = DeploymentPackageId;
            BlueDot.MsBuild.Tasks.MCorePackage.GetDependenciesResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).GetDependencies(inValue);
            return retVal.DependencyList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.RemoveDependencyResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.RemoveDependency(BlueDot.MsBuild.Tasks.MCorePackage.RemoveDependencyRequest request) {
            return base.Channel.RemoveDependency(request);
        }
        
        public void RemoveDependency(int PackageId, int DependentPackageId) {
            BlueDot.MsBuild.Tasks.MCorePackage.RemoveDependencyRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.RemoveDependencyRequest();
            inValue.PackageId = PackageId;
            inValue.DependentPackageId = DependentPackageId;
            BlueDot.MsBuild.Tasks.MCorePackage.RemoveDependencyResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).RemoveDependency(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlueDot.MsBuild.Tasks.MCorePackage.RegisterDeviceHandlerResponse BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign.RegisterDeviceHandler(BlueDot.MsBuild.Tasks.MCorePackage.RegisterDeviceHandlerRequest request) {
            return base.Channel.RegisterDeviceHandler(request);
        }
        
        public int RegisterDeviceHandler(BlueDot.MsBuild.Tasks.MCorePackage.DeviceHandlerModuleAddition NewHandlerModule) {
            BlueDot.MsBuild.Tasks.MCorePackage.RegisterDeviceHandlerRequest inValue = new BlueDot.MsBuild.Tasks.MCorePackage.RegisterDeviceHandlerRequest();
            inValue.NewHandlerModule = NewHandlerModule;
            BlueDot.MsBuild.Tasks.MCorePackage.RegisterDeviceHandlerResponse retVal = ((BlueDot.MsBuild.Tasks.MCorePackage.IPackageDesign)(this)).RegisterDeviceHandler(inValue);
            return retVal.DeviceHandlerId;
        }
    }
}
